routes/web.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('statistics', 'DashboardController@statistics')->name('dashboard.statistics');
    //admin users
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'User\UsersController@index')->name('index');
        Route::get('add', 'User\UsersController@create')->name('create');
        Route::post('add', 'User\UsersController@store')->name('store');
        Route::get('accounts', 'User\UserAccountsController@index')->name('accounts.index');
        Route::get('accounts/add', 'User\UserAccountsController@create')->name('accounts.create');
        Route::post('accounts/add', 'User\UserAccountsController@store')->name('accounts.store');
        Route::get('accounts/remove/{id}', 'User\UserAccountsController@delete')->name('accounts.delete');
        Route::get('accounts/edit/{id}', 'User\UserAccountsController@edit')->name('accounts.edit');
        Route::post('accounts/edit/{id}', 'User\UserAccountsController@update')->name('accounts.update');
        Route::get('accounts/search', 'User\UserAccountsController@search')->name('accounts.search');
        Route::get('search', 'User\UsersController@search');
        Route::get('delete', 'User\UsersController@delete');
    });
    //admin gateways
    Route::group(['prefix' => 'gateways'], function () {
        Route::get('/', 'Gateway\GatewaysController@index')->name('gateways.index');
        Route::get('add', 'Gateway\GatewaysController@create')->name('gateways.create');
        Route::post('add', 'Gateway\GatewaysController@store')->name('gateways.store');
        Route::get('reports', 'Gateway\ReportsController@index')->name('gateways.reports.index');
        Route::get('search', 'Gateway\GatewaysController@search')->name('gateways.search');

        Route::group(['prefix' => 'plans'], function () {
            Route::get('/', 'Gateway\PlansController@index')->name('gateways.plans.index');
            Route::get('add', 'Gateway\PlansController@create')->name('gateways.plans.create');
            Route::post('add', 'Gateway\PlansController@store')->name('gateways.plans.store');
        });
    });
    //admin withdrawals
    Route::group(['prefix' => 'withdrawals'], function () {
        Route::get('/', 'Withdrawal\WithdrawalsController@index')->name('withdrawals.index');
        Route::get('add', 'Withdrawal\WithdrawalsController@create')->name('withdrawals.create');
        Route::post('add', 'Withdrawal\WithdrawalsController@store')->name('withdrawals.store');
        Route::get('approve/{id}', 'Withdrawal\WithdrawalsController@approve')->name('withdrawals.approve');
        Route::post('approve/{id}',
            'Withdrawal\WithdrawalsController@performApprove')->name('withdrawals.approve.save');
        Route::get('reject/{id}', 'Withdrawal\WithdrawalsController@reject')->name('withdrawals.reject');
    });
    //admin transactions
    Route::group(['prefix' => 'transactions'], function () {
        Route::get('gateway', 'Transaction\GatewayTransactionsController@index')->name('transactions.gateway.index');
        Route::get('bank', 'Transaction\BankTransactionsController@index')->name('transactions.bank.index');
    });
    //admin payments
    Route::group(['prefix' => 'payments'], function () {
        Route::get('/', 'Payment\PaymentsController@index')->name('payments.index');
    });
    //admin settings
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'Setting\SettingsController@index')->name('settings.index');
        Route::get('create', 'Setting\SettingsController@create')->name('settings.create');
        Route::post('create', 'Setting\SettingsController@store')->name('settings.store');
    });

});
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    Route::get('pay/start', 'PaymentsController@start')->name('payment.start');
    Route::post('pay/verify/{payment_code}', 'PaymentsController@verify')->name('payment.verify');
    Route::post('transaction/request','Transaction\TransactionsController@request')->name('transaction.request');
    Route::get('transaction/start','Transaction\TransactionsController@start')->name('transaction.start');
    Route::post('transaction/verify','Transaction\TransactionsController@verify')->name('transaction.verify');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Filters\Contract\Filterable;
use App\Presenters\Contracts\Presentable;
use App\Presenters\User\UserPresenter;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, Presentable,Filterable;

    protected $presenter = UserPresenter::class;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /* Relations */
    public function accounts()
    {
        return $this->hasMany(UserAccount::class, 'user_account_user_id');
    }

    public function gateways()
    {
        return $this->hasMany(Gateway::class, 'gateway_user_id');
    }

    /* End Relations */
}

app/Http/Controllers/Admin/User/UserAccountsController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Models\UserAccount;
use App\Repositories\Contracts\GatewayRepositoryInterface;
use App\Repositories\Contracts\UserAccountRepositoryInterface;
use App\Repositories\Eloquent\Users\EloquentUserAccountRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class UserAccountsController extends Controller
{


    /**
     * @var UserAccountRepositoryInterface
     */
    private $user_account_repository;

    public function __construct(UserAccountRepositoryInterface $user_account_repository)
    {

        $this->user_account_repository = $user_account_repository;
    }

    public function index()
    {
        $userAccounts = $this->user_account_repository->all(null, ['owner']);

        return view('admin.user.account.index', compact('userAccounts'));
    }

    public function create()
    {
        $statuses = UserAccount::getStatuses();
        $userAccountItem = null;
        return view('admin.user.account.create', compact('statuses', 'userAccountItem'));
    }

    public function store(Request $request)
    {
        $newUserAccount = $this->user_account_repository->store([
            'user_account_user_id' => $request->owner,
            'user_account_title' => $request->title,
            'user_account_card_number' => $request->account_card,
            'user_account_sheba_number' => $request->account_sheba,
            'user_account_number' => $request->account_number,
            'user_account_status' => $request->account_status
        ]);
        if ($newUserAccount) {
            return back()->with('success', 'حساب جدید با موفقیت اضافه شد');
        }
    }

    public function delete(Request $request, $id)
    {
        $item = $this->user_account_repository->find($id);
        if ($item) {
            $item->delete();

            return back()->with('success', 'حساب بانکی مورد نظر با موفقیت حذف شد!');
        }

        return back()->withErrors([
            'invalid_user_account' => 'حساب کاربری مورد نظر معتبر نمی باشد!'
        ]);
    }

    public function edit(Request $request, $id)
    {
        $userAccountItem = $this->user_account_repository->find($id);
        if (!$userAccountItem) {
            return back()->withErrors([
                'invalid_user_account' => 'حساب کاربری معتبر نمی باشد!'
            ]);
        }
        $statuses = UserAccount::getStatuses();
        return view('admin.user.account.edit', compact('userAccountItem', 'statuses'));
    }

    public function search(Request $request)
    {
        $gateway_id = $request->gateway;
        $gateway_repository = resolve(GatewayRepositoryInterface::class);
        $gateway_item = $gateway_repository->find($gateway_id);
        $results = $this->user_account_repository->findBy([
            'user_account_user_id' => $gateway_item->gateway_user_id
        ], ['user_account_id as id', 'user_account_title as text'], false);
        //$htmlResult = view('admin.user.account.search',compact('results'))->render();
        return response()->json([
            'items' => $results
        ]);
    }
}

app/Http/Controllers/Admin/User/UsersController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Events\User\UserRegistered;
use App\Filters\UserFilters;
use App\Models\User;
use App\Repositories\Caching\CachingUserRepository;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Services\Notification\Facade\Notification;
use App\Services\Notification\NotificationService;
use App\Services\Notification\NotificationType;
use App\Services\User\UserCreateService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Redis;

class UsersController extends Controller
{
    private $usersRepository;

    public function __construct(UserRepositoryInterface $repository)
    {
        $this->usersRepository = $repository;

    }

    public function index(Request $request)
    {
        $users = $this->usersRepository->all();//(new CachingUserRepository())->all(); //User::filters(new UserFilters())->get(); //$this->usersRepository->all();
        //$views = Redis::incrBy('video.1.view',15);
//        Cache::remember
        return view('admin.user.index', compact('users'));
    }

    public function create()
    {

        return view('admin.user.create');
    }

    public function store(Request $request)
    {
        $userCreateService = new UserCreateService(
            [
                'name' => $request->name,
                'email' => $request->userEmail,
                'password' => $request->userPassword
            ]
        );

        $user_create_result = $userCreateService->perform();
        return redirect()->back()->with('success', $user_create_result);

    }

    public function search(Request $request)
    {
       $results = $this->usersRepository->searchUsers($request->search);
       return response()->json(['items' => $results]);
    }

    public function delete(Request $request)
    {
        $users = [];
        return view('admin.user.delete',compact('users'));
    }
}

app/Http/Controllers/Api/V1/UsersController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Api\Contracts\ApiController;
use App\Http\Resources\UserCollection;
use App\Http\Resources\UserResource;
use App\Models\User;
use App\Repositories\Contracts\UserRepositoryInterface;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends ApiController
{

    /**
     * @var UserRepositoryInterface
     */
    private $userRepository;

    public function __construct(UserRepositoryInterface $userRepository)
    {

        $this->userRepository = $userRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate();//$this->userRepository->paginate();
        return new UserCollection($users); //UserResource::collection($users);
//        return response()->json($users->toArray(),200,[
//            'Generated-BY'=>'Laravel Api'
//        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!$request->has('name'))
        {
           // return $this->res
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        if(!$user)
        {
            return $this->respondNoFound("User Not Found!");
        }
        return response()->json($user->toArray(),200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/account/columns.blade.php
<tr>
    <th scope="row">#</th>
    <th>صاحب کارت</th>
    <th>عنوان</th>
    <th>شماره حساب</th>
    <th>شماره شبا</th>
    <th>شماره کارت</th>
    <th>وضعیت</th>
    <th>عملیات</th>
</tr>

resources/views/admin/user/account/create.blade.php
@extends('layouts.admin')
@section('title','ایجاد حساب بانکی جدید')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endsection
@section('content')
    <div class="col-xs-12 col-md-9 col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>حساب های بانکی کاربران</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        @include('partials.errors')
                        @include('partials.success')
                        <div class="basic-form p-10">
                            <form method="post" action="{{ route('admin.users.accounts.store') }}"
                                  enctype="multipart/form-data">
                                @include('admin.user.account.form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
      jQuery(document).ready(function($) {
        $('#owner').select2({
          theme: 'classic',
          placeholder: 'جستجوی کاربران ...',
          minimumInputLength: 3,
          ajax: {
            url: '/admin/users/search',
            dataType: 'json',
            data: function(params) {
              return {
                search: params.term,
              };
            },
            processResults: function(data) {
              return {
                results: data.items,
              };
            },
          },
        });
      });
    </script>
@endsection

resources/views/admin/user/account/edit.blade.php
@extends('layouts.admin')
@section('title','ایجاد حساب بانکی جدید')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endsection
@section('content')
    <div class="col-xs-12 col-md-9 col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>حساب های بانکی کاربران</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        @include('partials.errors')
                        @include('partials.success')
                        <div class="basic-form p-10">
                            <form method="post" action="{{ route('admin.users.accounts.update',[$userAccountItem->user_account_id]) }}"
                                  enctype="multipart/form-data">
                                @include('admin.user.account.form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
      jQuery(document).ready(function($) {
        $('#owner').select2({
          theme: 'classic',
          placeholder: 'جستجوی کاربران ...',
          minimumInputLength: 3,
          ajax: {
            url: '/admin/users/search',
            dataType: 'json',
            data: function(params) {
              return {
                search: params.term,
              };
            },
            processResults: function(data) {
              return {
                results: data.items,
              };
            },
          },
        });
      });
    </script>
@endsection

resources/views/admin/user/account/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="owner">صاحب حساب :</label>
    <select name="owner" id="owner" class="form-control input-default"></select>
</div>
<div class="form-group">
    <label for="title">عنوان حساب :</label>
    <input id="title" name="title" type="text"
           class="form-control input-default"
           value="{{ old('title',!is_null($userAccountItem) ? $userAccountItem->user_account_title:'') }}">
</div>
<div class="form-group">
    <label for="account_number">شماره حساب</label>
    <input id="account_number" name="account_number" type="text"
           class="form-control input-default input-number"
           value="{{ old('account_number',!is_null($userAccountItem) ? $userAccountItem->user_account_account_number:'') }}">
</div>
<div class="form-group">
    <label for="account_sheba">
        شماره شبا
        <span class="form-label-description">(بدون IR)</span>
    </label>
    <input id="account_sheba" name="account_sheba" type="text"
           class="form-control input-default input-number"
           value="{{ old('account_sheba',!is_null($userAccountItem) ? $userAccountItem->user_account_sheba_number : '') }}">
</div>
<div class="form-group">
    <label for="account_card">شماره کارت</label>
    <input id="account_card" name="account_card" type="text"
           class="form-control input-default input-number"
           value="{{ old('account_card',!is_null($userAccountItem) ? $userAccountItem->user_account_card_number : '') }}">
</div>
<div class="form-group">
    <label for="account_status">وضعیت :</label>
    <select name="account_status" id="account_status" class="form-control">
        @foreach($statuses as $status => $title)
            <option value="{{ $status }}" {{ !is_null($userAccountItem) && $userAccountItem->user_account_status == $status ? 'selected' : ''  }}>{{ $title }}</option>
        @endforeach
    </select>
</div>
<div class="form-group m-t-20">
    <button type="submit" class="btn btn-primary m-b-10 m-l-5">ثبت اطلاعات
    </button>
</div>

resources/views/admin/user/account/index.blade.php
@extends('layouts.admin')
@section('title')
    لیست حساب های کاربران
@endsection
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>لیست حساب های کاربران </h4>
            </div>
            <div class="card-body">
                @include('admin.user.account.notifications')
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        @include('admin.user.account.columns')
                        </thead>
                        <tbody>
                        @each('admin.user.account.item',$userAccounts,'account')
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/account/item.blade.php
<tr>
    <th scope="row">{{ $account->user_account_id }}</th>
    <td>{{ $account->owner->name }}</td>
    <td>{{ $account->user_account_title }}</td>
    <td>{{ $account->present()->accountNumber }}</td>
    <td>{{ $account->present()->shebaNumber }}</td>
    <td>{{ $account->present()->cardNumber }}</td>
    <td>
        {!! $account->present()->adminStatus !!}
    </td>
    <td>
        <a href="{{ route('admin.users.accounts.delete',[$account->user_account_id]) }}"
           class="trash-item trash-user-account">
            <i class="fas fa-trash-alt"></i>
        </a>
        <a href="{{ route('admin.users.accounts.edit',[$account->user_account_id]) }}"
           class="trash-item trash-user-account">
            <i class="fas fa-edit"></i>
        </a>
    </td>
</tr>

resources/views/admin/user/account/notifications.blade.php
@include('partials.errors')
@include('partials.success')

resources/views/admin/user/account/search.blade.php
@foreach($results as $item)
    <option value="{{ $item->id }}">{{ $item->text }}</option>
@endforeach