routes/web.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('statistics', 'DashboardController@statistics')->name('dashboard.statistics');
    //admin users
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'User\UsersController@index')->name('index');
        Route::get('add', 'User\UsersController@create')->name('create');
        Route::post('add', 'User\UsersController@store')->name('store');
        Route::get('accounts', 'User\UserAccountsController@index')->name('accounts.index');
        Route::get('accounts/add', 'User\UserAccountsController@create')->name('accounts.create');
        Route::post('accounts/add', 'User\UserAccountsController@store')->name('accounts.store');
        Route::get('accounts/remove/{id}', 'User\UserAccountsController@delete')->name('accounts.delete');
        Route::get('accounts/edit/{id}', 'User\UserAccountsController@edit')->name('accounts.edit');
        Route::post('accounts/edit/{id}', 'User\UserAccountsController@update')->name('accounts.update');
        Route::get('accounts/search', 'User\UserAccountsController@search')->name('accounts.search');
        Route::get('search', 'User\UsersController@search');
        Route::get('delete', 'User\UsersController@delete');
    });
    //admin gateways
    Route::group(['prefix' => 'gateways'], function () {
        Route::get('/', 'Gateway\GatewaysController@index')->name('gateways.index');
        Route::get('add', 'Gateway\GatewaysController@create')->name('gateways.create');
        Route::post('add', 'Gateway\GatewaysController@store')->name('gateways.store');
        Route::get('reports', 'Gateway\ReportsController@index')->name('gateways.reports.index');
        Route::get('search', 'Gateway\GatewaysController@search')->name('gateways.search');

        Route::group(['prefix' => 'plans'], function () {
            Route::get('/', 'Gateway\PlansController@index')->name('gateways.plans.index');
            Route::get('add', 'Gateway\PlansController@create')->name('gateways.plans.create');
            Route::post('add', 'Gateway\PlansController@store')->name('gateways.plans.store');
        });
    });
    //admin withdrawals
    Route::group(['prefix' => 'withdrawals'], function () {
        Route::get('/', 'Withdrawal\WithdrawalsController@index')->name('withdrawals.index');
        Route::get('add', 'Withdrawal\WithdrawalsController@create')->name('withdrawals.create');
        Route::post('add', 'Withdrawal\WithdrawalsController@store')->name('withdrawals.store');
        Route::get('approve/{id}', 'Withdrawal\WithdrawalsController@approve')->name('withdrawals.approve');
        Route::post('approve/{id}',
            'Withdrawal\WithdrawalsController@performApprove')->name('withdrawals.approve.save');
        Route::get('reject/{id}', 'Withdrawal\WithdrawalsController@reject')->name('withdrawals.reject');
    });
    //admin transactions
    Route::group(['prefix' => 'transactions'], function () {
        Route::get('gateway', 'Transaction\GatewayTransactionsController@index')->name('transactions.gateway.index');
        Route::get('bank', 'Transaction\BankTransactionsController@index')->name('transactions.bank.index');
    });
    //admin payments
    Route::group(['prefix' => 'payments'], function () {
        Route::get('/', 'Payment\PaymentsController@index')->name('payments.index');
    });
    //admin settings
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'Setting\SettingsController@index')->name('settings.index');
        Route::get('create', 'Setting\SettingsController@create')->name('settings.create');
        Route::post('create', 'Setting\SettingsController@store')->name('settings.store');
    });

});
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    Route::get('pay/start', 'PaymentsController@start')->name('payment.start');
    Route::post('pay/verify/{payment_code}', 'PaymentsController@verify')->name('payment.verify');
    Route::post('transaction/request','Transaction\TransactionsController@request')->name('transaction.request');
    Route::get('transaction/start','Transaction\TransactionsController@start')->name('transaction.start');
    Route::post('transaction/verify','Transaction\TransactionsController@verify')->name('transaction.verify');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Gateway.php
<?php

namespace App\Models;

use App\Filters\Contract\Filterable;
use Illuminate\Database\Eloquent\Model;

class Gateway extends Model
{
    use Filterable;
    const ACTIVE = 1;
    const INACTIVE = 0;

    protected $primaryKey = 'gateway_id';

    protected $guarded = ['gateway_id'];

    /*Relations*/

    public static function getStatuses()
    {
        return [
            self::ACTIVE   => 'فعال',
            self::INACTIVE => 'غیر فعال '
        ];
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class, 'gateway_plan')->withDefault([
            'gateway_plan_title' => 'طرح نقره ای '
        ]);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'gateway_user_id');
    }

    public function withdrawals()
    {
        return $this->hasMany(Withdrawal::class, 'withdrawal_gateway_id');
    }

    public function transactions()
    {
        return $this->hasMany(GatewayTransaction::class,'gateway_transaction_gateway_id');
    }

    /*End Relations*/

    public function aggregations()
    {
        return $this->hasMany(GatewayReport::class, 'gateway_report_gateway_id');
    }
}

app/Http/Controllers/Admin/Gateway/GatewaysController.php
<?php

namespace App\Http\Controllers\Admin\Gateway;

use App\Filters\GatewayFilters;
use App\Models\Gateway;
use App\Repositories\Contracts\GatewayRepositoryInterface;
use App\Repositories\Contracts\PlanRepositoryInterface;
use App\Services\Gateway\CreateGatewayRequest;
use App\Services\Gateway\CreateGatewayService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GatewaysController extends Controller
{
    /**
     * @var GatewayRepositoryInterface
     */
    private $gatewayRepository;
    /**
     * @var PlanRepositoryInterface
     */
    private $plan_repository;

    public function __construct(
        GatewayRepositoryInterface $gatewayRepository,
        PlanRepositoryInterface $plan_repository
    ) {

        $this->gatewayRepository = $gatewayRepository;
        $this->plan_repository = $plan_repository;
    }

    public function index()
    {

        $gateways = Gateway::filters(new GatewayFilters())->get(); //$this->gatewayRepository->all(null, ['user', 'plan']);

        return view('admin.gateway.index', compact('gateways'));
    }

    public function create()
    {
        $statuses = $this->gatewayRepository->getStatuses();
        $plans = $this->plan_repository->all();
        $gatewayItem = null;

        return view('admin.gateway.create', compact('statuses', 'gatewayItem', 'plans'));

    }

    public function store(Request $request)
    {
        $createGatewayService = new CreateGatewayService(
            new CreateGatewayRequest(
                [
                    'user' => $request->input('owner'),
                    'plan' => $request->input('plan'),
                    'title' => $request->input('title'),
                    'website' => $request->input('website'),
                    'status' => $request->input('status')
                ]
            )
        );
        $newGateway = $createGatewayService->perform();
        if ($newGateway) {
            return back()->with('success', 'درگاه جدید با موفقیت ثبت گردید');
        }
    }

    public function search(Request $request)
    {
        $term = $request->search;
        $results = $this->gatewayRepository->search($term);
        return response()->json(['items' => $results]);
    }
}

app/Http/Controllers/Admin/Gateway/PlansController.php
<?php

namespace App\Http\Controllers\Admin\Gateway;

use App\Repositories\Contracts\PlanRepositoryInterface;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PlansController extends Controller
{

    /**
     * @var PlanRepositoryInterface
     */
    private $plan_repository;

    public function __construct(PlanRepositoryInterface $plan_repository)
    {

        $this->plan_repository = $plan_repository;
    }

    public function index()
    {
        $plans = $this->plan_repository->all();

        return view('admin.gateway.plan.index', compact('plans'));
    }

    public function create()
    {
        return view('admin.gateway.plan.create');
    }

    public function store(Request $request)
    {
        $newPlan = $this->plan_repository->store([
            'gateway_plan_title'           => $request->plan_title,
            'gateway_plan_commission'      => $request->plan_commission,
            'gateway_plan_withdrawal_rate' => $request->plan_withdrawal_rate,
            'gateway_plan_withdrawal_max'  => $request->plan_withdrawal_max
        ]);
        if ($newPlan) {
            return back()->with('success', 'طرح جدید با موفقیت ایجاد شد');
        }
    }
}

app/Http/Controllers/Admin/Gateway/ReportsController.php
<?php

namespace App\Http\Controllers\Admin\Gateway;

use App\Repositories\Contracts\GatewayAggregationRepositoryInterface;
use App\Repositories\Eloquent\Gateway\EloquentGatewayAggregationRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReportsController extends Controller
{
    /**
     * @var GatewayAggregationRepositoryInterface
     */
    private $gatewayAggregationRepository;

    public function __construct(GatewayAggregationRepositoryInterface $gatewayAggregationRepository)
    {

        $this->gatewayAggregationRepository = $gatewayAggregationRepository;
    }

    public function index()
    {
        $reports = $this->gatewayAggregationRepository->all(null, ['gateway.user']);
        return view('admin.gateway.report.index', compact('reports'));
    }
}

resources/views/admin/gateway/columns.blade.php
<tr>
    <th>#</th>
    <th>طرح</th>
    <th>کاربر</th>
    <th>عنوان</th>
    <th>وب سایت</th>
    <th>موجودی</th>
    <th>وضعیت</th>
</tr>

resources/views/admin/gateway/create.blade.php
@extends('layouts.admin')
@section('title','ایجاد درگاه جدید')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endsection
@section('content')
    <div class="col-xs-12 col-md-9 col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>ایجاد درگاه جدید</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        @include('partials.errors')
                        @include('partials.success')
                        <div class="basic-form p-10">
                            <form method="post" action="{{ route('admin.gateways.store') }}"
                                  enctype="multipart/form-data">
                                @include('admin.gateway.form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        jQuery(document).ready(function($) {
            $('#owner').select2({
                theme: 'classic',
                placeholder: 'جستجوی کاربران ...',
                minimumInputLength: 3,
                ajax: {
                    url: '/admin/users/search',
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                        };
                    },
                    processResults: function(data) {
                        return {
                            results: data.items,
                        };
                    },
                },
            });
        });
    </script>
@endsection

resources/views/admin/gateway/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="owner">صاحب درگاه :</label>
    <select name="owner" id="owner" class="form-control input-default"></select>
</div>
<div class="form-group">
    <label for="plan">طرح درگاه :</label>
    <select name="plan" id="plan" class="form-control input-default">
        @foreach($plans as $plan)
            <option value="{{ $plan->gateway_plan_id }}">{{ $plan->gateway_plan_title }}</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label for="title">عنوان درگاه :</label>
    <input id="title" name="title" type="text"
           class="form-control input-default"
           value="{{ old('title',!is_null($gatewayItem) ? $gatewayItem->user_account_title:'') }}">
</div>
<div class="form-group">
    <label for="website">وب سایت درگاه :</label>
    <input id="website" name="website" type="text"
           class="form-control input-default input-number"
           value="{{ old('website',!is_null($gatewayItem) ? $gatewayItem->user_account_account_number:'') }}">
</div>
<div class="form-group">
    <label for="status">وضعیت :</label>
    <select name="status" id="status" class="form-control">
        @foreach($statuses as $status => $title)
            <option value="{{ $status }}" {{ !is_null($gatewayItem) && $gatewayItem->user_account_status == $status ? 'selected' : ''  }}>{{ $title }}</option>
        @endforeach
    </select>
</div>
<div class="form-group m-t-20">
    <button type="submit" class="btn btn-primary m-b-10 m-l-5">ثبت اطلاعات
    </button>
</div>

resources/views/admin/gateway/index.blade.php
@extends('layouts.admin')
@section('title') لیست درگاه ها @endsection
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>لیست درگاه ها</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            @include('admin.gateway.columns')
                        </thead>
                        <tbody>
                            @each('admin.gateway.item',$gateways,'gateway')
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/gateway/item.blade.php
<tr>
    <th scope="row">{{ $gateway->gateway_id }}</th>
    <td>{{ $gateway->plan->gateway_plan_title }}</td>
    <td>{{ $gateway->user->name }}</td>
    <td>{{ $gateway->gateway_title }}</td>
    <td>{{ $gateway->gateway_website }}</td>
    <td>{{ $gateway->gateway_balance }}</td>
    <td>{{ $gateway->gateway_status }}</td>
</tr>